import type { Metadata } from "next";
import { Inter, Lora, Inconsolata } from "next/font/google";
import "./globals.css";
import { ThemeProviders } from "./context/components/theme/ThemeProviders";
import Navbar from "./context/components/Navbar";
import { AppProvider } from "./context/components/app/AppContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const lora = Lora({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lora",
});

const inconsolata = Inconsolata({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inconsolata",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${lora.variable} ${inconsolata.variable} font-sans container mx-auto max-w-[768px] px-6 py-14 dark:bg-black`}>
        <ThemeProviders>
          <AppProvider>
            <Navbar />
            {children}
          </AppProvider>
        </ThemeProviders>
      </body>
    </html>
  );
}
